version: '3.8'

services:
  backend:
    image: hahongson/cookie-violation-checker-backend:latest
    container_name: fastapi_backend
    ports:
      - "8001:8001"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    image: hahongson/cookie-violation-checker-frontend:latest
    container_name: react_frontend
    ports:
      - "3001:80"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongodb_db
    ports:
      - "27018:27018"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
