services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_backend
    ports:
      - "9130:8000"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - docker-net

  frontend:
    build:
      context: ./frontend/cookie-compliance-frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    container_name: react_frontend
    ports:
      - "9131:80"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - docker-net

  mongo:
    image: mongo:latest
    container_name: mongodb_db
    ports:
      - "9133:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - docker-net

networks:
  docker-net:
    driver: bridge

volumes:
  mongo_data:
